---
- name: Configurer et monter un nouveau disque sur Ubuntu
  hosts: votre_hote
  become: true
  tasks:
    - name: Partitionner le disque
      parted:
        device: /dev/sdb
        number: 1
        state: present
      register: disk_partition_result

    - name: Créer un système de fichiers ext3
      filesystem:
        fstype: ext3
        dev: /dev/sdb1
      when: disk_partition_result.changed

    - name: Créer le répertoire de montage
      file:
        path: /chemin/vers/votre/point/de/montage
        state: directory

    - name: Monter le disque
      mount:
        path: /chemin/vers/votre/point/de/montage
        src: /dev/sdb1
        fstype: ext3
        state: mounted


---
# vars.yml
nfs_clients:
  - 192.168.1.100
  - 192.168.1.101

nfs_export_path: "/chemin/vers/repertoire/export"

---
- name: Installer et configurer le serveur NFS
  hosts: votre_hote
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Installer le serveur NFS
      apt:
        name: nfs-kernel-server
        state: present

    - name: Créer le répertoire d'export NFS
      file:
        path: "{{ nfs_export_path }}"
        state: directory

    - name: Configurer les exportations NFS
      lineinfile:
        path: /etc/exports
        line: "{{ nfs_export_path }} {{ item }}(rw,sync,no_subtree_check)"
        state: present
      with_items: "{{ nfs_clients }}"
      notify: Redémarrer le serveur NFS

  handlers:
    - name: Redémarrer le serveur NFS
      systemd:
        name: nfs-kernel-server
        state: restarted




